#!/usr/bin/env ruby

require './lib/moyskladsync'

module Moyskladsync
  ms_client = Clients::Moysklad.new(ENV['MOYSKLAD_LOGIN'], ENV['MOYSKLAD_PASS'])

  json_io = StringIO.new(ENV['GCLOUD_SECRET'])
  google_client = Clients::Gdrive.new(json_io, ENV['GCLOUD_DOCUMENT_ID'])

  Sync.new(source: ms_client, destination: google_client).start!
end
